pub const OPEN_PAREN: char = '(';
pub const CLOSED_PAREN: char = ')';
pub const OPEN_CBR: char = '{';
pub const CLOSED_CBR: char = '}';
pub const OPEN_BR: char = '[';
pub const CLOSED_BR: char = ']';
pub const NL: char = '\n';
pub const DOUBLE_QUOTES: char = '"';
pub const SPACE: char = ' ';
pub const DOT: char = '.';
pub const COLON: char = ':';
pub const SEMICOLON: char = ';';
pub const FORWARD_SLASH: char = '/';
pub const BACKSLASH: char = '\\';
pub const MINUS: char = '-';
pub const PLUS: char = '+';
pub const MOD: char = '%';
pub const STAR: char = '*';
pub const GREATER_THAN: char = '>';
pub const LESS_THAN: char = '<';
pub const EQUALS: char = '=';
pub const UNDERSCORE: char = '_';
pub const COMMA: char = ',';

pub const FUN: &str = "fun";
pub const VAR: &str = "var";
pub const MUT: &str = "mut";
pub const RETURN: &str = "return";
pub const IF: &str = "if";
pub const ELSE: &str = "else";
pub const INT: &str = "int";
pub const FLOAT: &str = "float";
pub const LOOP: &str = "loop";
pub const BREAK: &str = "break";

pub const TRUE: &str = "true";
pub const FALSE: &str = "false";
